import { inflateRawSync } from 'node:zlib';
import { Buffer } from 'node:buffer';
const escape = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
const unescape = s => s.replace(/&#x([\da-f]+);|&#(\d+);|&(amp|lt|gt|quot|apos);/gi, (_,h,n,k)=>h?String.fromCodePoint(parseInt(h,16)):n?String.fromCodePoint(+n):({amp:'&',lt:'<',gt:'>',quot:'"',apos:"'"}[k]));
const table=Array.from({length:256},(_,n)=>{for(let k=0;k<8;k++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0});
function crc(b){let n=0xffffffff;for(const x of b)n=table[(n^x)&255]^(n>>>8);return (n^0xffffffff)>>>0}
export function zip(files){let offset=0;const local=[],central=[];for(const [name,value] of Object.entries(files)){const n=Buffer.from(name),b=Buffer.from(value),l=Buffer.alloc(30),c=Buffer.alloc(46);l.writeUInt32LE(0x04034b50);l.writeUInt16LE(20,4);l.writeUInt32LE(crc(b),14);l.writeUInt32LE(b.length,18);l.writeUInt32LE(b.length,22);l.writeUInt16LE(n.length,26);c.writeUInt32LE(0x02014b50);c.writeUInt16LE(20,4);c.writeUInt16LE(20,6);c.writeUInt32LE(crc(b),16);c.writeUInt32LE(b.length,20);c.writeUInt32LE(b.length,24);c.writeUInt16LE(n.length,28);c.writeUInt32LE(offset,42);local.push(l,n,b);central.push(c,n);offset+=l.length+n.length+b.length}const end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(Object.keys(files).length,8);end.writeUInt16LE(Object.keys(files).length,10);end.writeUInt32LE(central.reduce((a,b)=>a+b.length,0),12);end.writeUInt32LE(offset,16);return Buffer.concat([...local,...central,end])}
export function unzip(buf){let end=-1;for(let i=buf.length-22;i>=Math.max(0,buf.length-65557);i--){if(buf.readUInt32LE(i)===0x06054b50){end=i;break}}if(end<0)throw Error('No es un archivo Excel .xlsx válido.');let p=buf.readUInt32LE(end+16),total=0;const files={};const count=buf.readUInt16LE(end+10);if(count>2000)throw Error('El archivo contiene demasiados elementos.');for(let i=0;i<count;i++){if(buf.readUInt32LE(p)!==0x02014b50)throw Error('Archivo ZIP dañado.');const method=buf.readUInt16LE(p+10),size=buf.readUInt32LE(p+20),raw=buf.readUInt32LE(p+24),nl=buf.readUInt16LE(p+28),el=buf.readUInt16LE(p+30),cl=buf.readUInt16LE(p+32),off=buf.readUInt32LE(p+42);total+=raw;if(total>30e6)throw Error('Excel demasiado grande (máximo 30 MB descomprimido).');const name=buf.subarray(p+46,p+46+nl).toString();const start=off+30+buf.readUInt16LE(off+26)+buf.readUInt16LE(off+28);const compressed=buf.subarray(start,start+size);if(method!==0&&method!==8)throw Error('Compresión Excel no compatible.');files[name]=(method===0?compressed:inflateRawSync(compressed,{maxOutputLength:30e6})).toString('utf8');p+=46+nl+el+cl}return files}
function col(n){let s='';for(n++;n;n=Math.floor((n-1)/26))s=String.fromCharCode(65+(n-1)%26)+s;return s}
export function workbook(sheets){const files={};files['[Content_Types].xml']='<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>'+sheets.map((_,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join('')+'</Types>';files['_rels/.rels']='<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>';files['xl/workbook.xml']='<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>'+sheets.map((s,i)=>`<sheet name="${escape(s.name)}" sheetId="${i+1}" r:id="rId${i+1}"/>`).join('')+'</sheets></workbook>';files['xl/_rels/workbook.xml.rels']='<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'+sheets.map((_,i)=>`<Relationship Id="rId${i+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join('')+'</Relationships>';for(const [i,s] of sheets.entries())files[`xl/worksheets/sheet${i+1}.xml`]='<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols><col min="1" max="30" width="28" customWidth="1"/></cols><sheetData>'+s.rows.map((row,r)=>`<row r="${r+1}">${row.map((v,c)=>typeof v==='number'?`<c r="${col(c)}${r+1}"><v>${v}</v></c>`:`<c r="${col(c)}${r+1}" t="inlineStr"><is><t xml:space="preserve">${escape(v)}</t></is></c>`).join('')}</row>`).join('')+'</sheetData></worksheet>';return zip(files)}
export function readWorkbook(buffer){const f=unzip(buffer),shared=[...(f['xl/sharedStrings.xml']||'').matchAll(/<si(?:\s[^>]*)?>([\s\S]*?)<\/si>/g)].map(m=>[...m[1].matchAll(/<t(?:\s[^>]*)?>([\s\S]*?)<\/t>/g)].map(t=>unescape(t[1])).join(''));const sheets=Object.keys(f).filter(n=>/^xl\/worksheets\/sheet\d+\.xml$/.test(n)).sort();if(!sheets.length)throw Error('No se han encontrado hojas de cálculo.');return sheets.map(name=>{const rows=[];for(const row of f[name].matchAll(/<row\b[^>]*>([\s\S]*?)<\/row>/g)){const values=[];for(const c of row[1].matchAll(/<c\b([^>]*)>([\s\S]*?)<\/c>/g)){const ref=/\br="([A-Z]+)\d+"/.exec(c[1]);if(!ref)continue;let idx=0;for(const x of ref[1])idx=idx*26+x.charCodeAt(0)-64;const v=/<v(?:\s[^>]*)?>([\s\S]*?)<\/v>/.exec(c[2])?.[1]||'';values[idx-1]=/\bt="s"/.test(c[1])?shared[+v]||'':/\bt="inlineStr"/.test(c[1])?[...c[2].matchAll(/<t(?:\s[^>]*)?>([\s\S]*?)<\/t>/g)].map(t=>unescape(t[1])).join(''):unescape(v)}rows.push(values)}return rows})}
